# Generated by Django 5.1 on 2024-09-14 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('LoL', 'League of Legends'), ('VL', 'Valorant'), ('D2', 'Dota2'), ('CSGO', 'Counter-Strike: Global Offensive'), ('OV', 'Overwach'), ('FT', 'Fornite'), ('R6', 'Rainbow Six Siege'), ('FF', 'FIFA'), ('CR', 'Clash Royale')], max_length=5)),
                ('rank', models.CharField(max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_played', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
