# Generated by Django 5.1 on 2024-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
