# Generated by Django 5.1 on 2024-10-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sponsorproducts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='viltrum_rank',
            field=models.CharField(choices=[('E', 'Elite'), ('S', 'Sakura'), ('S+', 'Sakura +'), ('V', 'Viltrum'), ('V+', 'Viltrum +')], default='E', max_length=3),
        ),
    ]
