# Generated by Django 5.1 on 2024-09-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_playerstats_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='user_game',
            field=models.CharField(default='DEFAULT', max_length=50),
            preserve_default=False,
        ),
    ]
