# Generated by Django 5.1.1 on 2024-10-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message_usergalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergalleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
    ]
