# Generated by Django 5.0.8 on 2024-10-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usergalleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='user_verification',
            field=models.BooleanField(default=False),
        ),
    ]
