# Generated by Django 5.1 on 2024-09-19 17:54

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_playerstats_user_alter_playerstats_user_game_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games/covers/')),
            ],
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/profilebanner'),
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profileimg'),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='game',
            field=models.CharField(choices=[('LoL', 'League of Legends'), ('D2', 'Dota 2'), ('CSGO', 'Counter-Strike: Global Offensive'), ('VAL', 'Valorant'), ('OW', 'Overwatch'), ('PUBG', "PlayerUnknown's Battlegrounds"), ('FORT', 'Fortnite'), ('Apex', 'Apex Legends'), ('R6', 'Rainbow Six Siege'), ('RL', 'Rocket League')], max_length=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='user_game',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.game')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='users.game')),
            ],
        ),
    ]
