# Generated by Django 5.1 on 2024-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_playerstats_user_alter_playerstats_user_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/profilebanner'),
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profileimg'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='game',
            field=models.CharField(choices=[('LoL', 'League of Legends'), ('D2', 'Dota 2'), ('CSGO', 'Counter-Strike: Global Offensive'), ('VAL', 'Valorant'), ('OW', 'Overwatch'), ('PUBG', "PlayerUnknown's Battlegrounds"), ('FORT', 'Fortnite'), ('Apex', 'Apex Legends'), ('R6', 'Rainbow Six Siege'), ('RL', 'Rocket League')], max_length=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='user_game',
            field=models.CharField(max_length=50),
        ),
    ]
