# Generated by Django 5.1 on 2024-10-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_extendeddata_user_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='user_identification',
            field=models.ImageField(null=True, upload_to='identification'),
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='verification_photo'),
        ),
    ]
