# Generated by Django 5.1 on 2024-09-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sponsorproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorproducts',
            name='product_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorproducts',
            name='product_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
