# Generated by Django 5.1.3 on 2024-11-17 20:12

import storages.backends.azure_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_sponsorship_sponsors_sponsorship_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(), upload_to='images/profilebanner'),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(), upload_to='images/profileimg'),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='user_identification',
            field=models.ImageField(null=True, storage=storages.backends.azure_storage.AzureStorage(), upload_to='identification'),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='user_photo',
            field=models.ImageField(null=True, storage=storages.backends.azure_storage.AzureStorage(), upload_to='verification_photo'),
        ),
        migrations.AlterField(
            model_name='sponsorproducts',
            name='product_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(), upload_to='images/sponsorProducts'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='imagen',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(), upload_to='streams/'),
        ),
        migrations.AlterField(
            model_name='usergalleryimage',
            name='image',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(), upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='portada',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(), upload_to='portadas/'),
        ),
    ]
