# Generated by Django 5.1.1 on 2024-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification_delete_torneo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/tournament_banners/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('Warzone', 'Call of Duty: Warzone'), ('Albion', 'Albion Online'), ('Fortnite', 'Fortnite')], max_length=50),
        ),
    ]
