# Generated by Django 5.1.1 on 2024-09-23 17:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tournament_banner_alter_tournament_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.AddField(
            model_name='tournament',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 17, 52, 29, 695732, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_banners/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('game1', 'Game 1'), ('game2', 'Game 2'), ('game3', 'Game 3')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_members',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
