# Generated by Django 5.1 on 2024-10-06 17:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game', models.CharField(choices=[('LoL', 'League of Legends'), ('D2', 'Dota 2'), ('CSGO', 'Counter-Strike: Global Offensive'), ('VAL', 'Valorant'), ('OW', 'Overwatch'), ('PUBG', "PlayerUnknown's Battlegrounds"), ('FORT', 'Fortnite'), ('Apex', 'Apex Legends'), ('R6', 'Rainbow Six Siege'), ('RL', 'Rocket League')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_deadline', models.DateTimeField(default=datetime.datetime(2024, 10, 9, 17, 58, 34, 206745, tzinfo=datetime.timezone.utc))),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, max_length=20)),
                ('max_members', models.IntegerField(default=10)),
                ('members', models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], db_index=True, default='P', max_length=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tournament'), name='unique_user_tournament')],
            },
        ),
    ]
