# Generated by Django 5.1 on 2024-10-06 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 18, 4, 30, 255058, tzinfo=datetime.timezone.utc)),
        ),
    ]
