# Generated by Django 5.1.1 on 2024-10-02 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 4, 22, 17, 63128, tzinfo=datetime.timezone.utc)),
        ),
    ]
