# Generated by Django 5.1 on 2024-10-02 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clasificacion',
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='banner',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 28, 57, 299552, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
    ]
