# Generated by Django 5.1 on 2024-10-02 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_delete_clasificacion_remove_gameimage_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('LoL', 'League of Legends'), ('D2', 'Dota 2'), ('CSGO', 'Counter-Strike: Global Offensive'), ('VAL', 'Valorant'), ('OW', 'Overwatch'), ('PUBG', "PlayerUnknown's Battlegrounds"), ('FORT', 'Fortnite'), ('Apex', 'Apex Legends'), ('R6', 'Rainbow Six Siege'), ('RL', 'Rocket League')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 32, 3, 122697, tzinfo=datetime.timezone.utc)),
        ),
    ]
