# Generated by Django 5.0.8 on 2024-10-18 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 0, 38, 53, 154920, tzinfo=datetime.timezone.utc)),
        ),
    ]
