# Generated by Django 5.1.1 on 2024-10-16 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 3, 29, 52, 42117, tzinfo=datetime.timezone.utc)),
        ),
    ]
