# Generated by Django 5.1.1 on 2024-10-16 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 3, 39, 42, 504235, tzinfo=datetime.timezone.utc)),
        ),
    ]
