# Generated by Django 5.0.8 on 2024-10-21 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 22, 42, 0, 314150, tzinfo=datetime.timezone.utc)),
        ),
    ]
