# Generated by Django 5.0.8 on 2024-10-03 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_tournament_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 21, 30, 53, 457879, tzinfo=datetime.timezone.utc)),
        ),
    ]
