# Generated by Django 5.0.8 on 2024-11-11 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 17, 15, 45, 828037, tzinfo=datetime.timezone.utc)),
        ),
    ]
