# Generated by Django 5.1.3 on 2024-11-12 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_tournament_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 45, 14, 931224, tzinfo=datetime.timezone.utc)),
        ),
    ]
