# Generated by Django 5.1.3 on 2024-11-17 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 20, 12, 5, 113430, tzinfo=datetime.timezone.utc)),
        ),
    ]
