# Generated by Django 5.1.3 on 2024-11-19 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 15, 39, 32, 750445, tzinfo=datetime.timezone.utc)),
        ),
    ]
