# Generated by Django 5.1.1 on 2024-10-02 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('viltrum_rank', models.CharField(choices=[('E', 'Elite'), ('S', 'Sakura'), ('S+', 'Sakura +'), ('V', 'Viltrum'), ('V+', 'Viltrum +')], max_length=10)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('total_played', models.IntegerField()),
                ('user_game', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasifications_playerstats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
